a=input('Enter the first number: ')
b=input('Enter the second number: ')
a=int(a)
b=int(b)
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
print("addition=",addition)
print("subtraction=",subtraction)
print("multiplication=",multiplication)
print("division=",division)